# Generated by Django 4.0.2 on 2022-02-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('logo', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(max_length=156)),
                ('floor', models.CharField(blank=True, max_length=32, null=True)),
                ('shop_number', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('reg_at', models.DateTimeField(auto_now_add=True)),
                ('open_at', models.TimeField(blank=True, null=True)),
                ('close_at', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
